user_data_dir = "~/.config/google-chrome"
cookies_path = ""
cf_worker = ""
timeout = 30
sleep = 0.1
chat = false
skip_known = false
graduate = 23
salary_max = 10
active_block_list = ["半年", "月内", "本月", "周内", "本周", "7日"]
scale_block_list = ["-20"]
degree_block_list = ["硕", "博"]
experience_block_list = ["5", "10"]
city_block_list = [
    "沈阳",
    "辽宁",
    "辽阳",
    "齐齐哈尔",
    "塔城",
    "长春",
    "毕节",
    "包头",
    "乌鲁木齐",
    "拉萨",
    "锡林",
    "葫芦",
    "乌兰察布",
    "大连",
    "大庆",
    "通辽",
    "哈尔滨",
    "呼和浩特",
    "鄂尔多斯",
    "西宁",
    "汉中",
    "沧州",
    "莆田",
    "伊犁",
    "布克",
    "塔城",
    "和丰",
    "喀什",
    "自治",
    "苗族",
    "黔",
    "兴义",
    "东营",
    "学院",
    "清远",
    "丹东",
    "丽水",
    "平顶山",
]
boss_title_block_list = ["总裁", "总经理", "ceo", "创始人", "法人"]
industry_block_list = ["培训", "教育", "院校", "房产", "经纪", "工程施工", "批发", "零售", "再生资源"]
name_block_list = [
    "可靠",
    "光源",
    "打光",
    "梳理",
    "材料",
    "预结算",
    "安装",
    "检测",
    "轮班",
    "倒班",
    "夜班",
    "保洁",
    "酒店",
    "监控",
    "声音",
    "设备",
    "党建",
    "宣传",
    "招聘",
    "人事",
    "质控",
    "手机检测",
    "产品助理",
    "项目助理",
    "人事助理",
    "桌面运维",
    "开发专员",
    "安卓开发",
    "上门",
    "aoi",
    "n2",
    "leader",
    "整机",
    "笔电",
    "结构",
    "衡器",
    "dqe",
    "厂区",
    "轻松",
    "运营助理",
    "亚马逊",
    "专利",
    "代理",
    "舆情",
    "处理",
    "生产",
    "装备",
    "助教",
    "销售",
    "日",
    "陪产",
    "量化",
    "统计",
    "商务",
    "服装",
    "选址",
    "外贸",
    "实验",
    "弱电",
    "食品",
    "学徒",
    "前台",
    "导购",
    "消防",
    "暖通",
    "电气",
    "机电",
    "售前",
    "售后",
    "二维",
    "动画",
    "仪器",
    "机械",
    "器械",
    "耗材",
    "硬件",
    "教师",
    "讲师",
    "餐饮",
    "必胜客",
    "人力",
    "文员",
    "机房",
    "农业",
    "林业",
    "直播",
    "老师",
    "推广",
    "测量",
    "操作工",
    "病理",
    "元器件",
    "技术员",
    "实训",
    "经营",
    "对账",
    "培训",
    "训练",
    "残",
    "创业",
    "合伙",
    "光学",
    "座舱",
    "车",
    "经理",
    "基金",
    "三维",
    "芯片",
    "布料",
    "市场",
    "obc",
    "环保",
    "财务",
    "采购",
    "人士",
    "管家",
    "水务",
    "棋牌",
    "资深",
    "专家",
    "兼职",
    "台湾",
    "香港",
    "海外",
    "驾驶",
    "无人",
    "高薪",
    "egp",
    "通信",
    "外派",
    "企点",
    "造价",
    "期刊",
    "玩具",
    "电动",
    "运营",
    "发单",
    "护士",
    "面料",
    "粤语",
    "内窥",
    "装修",
    "家装",
    "施工",
    "税务",
    "图像",
    "设计师",
    "生信",
    "室内",
    "行政",
    "客服",
    "拍摄",
    "剪辑",
    "理疗",
    "美容",
    "数据员",
    "制图员",
    "调测员",
    "新媒体",
    "道路",
    "安防",
    "展厅",
    "买手",
    "微信",
    "数通",
    "维修",
    "打单",
    "单证",
    "节目",
    "智库",
    "法务",
    "部门",
    "资料",
    "分诊",
    "录入",
    "签证",
    "物流",
    "标注",
    "建筑",
    "惠普",
    "速卖通",
    "电商助理",
    "营销",
    "经销",
    "城市规划",
    "质检",
    "回收",
    "无人机",
    "小白",
    "收银",
    "bim",
    "caxa",
    "跟线",
    "管理",
    "审计",
    "样品",
    "组长",
    "主管",
    "高级",
    "渗透",
    "爬虫",
    "网络",
    "游戏",
    "架构",
    "英文",
    "英语",
    "单片机",
    "嵌入式软件开发",
    "qt",
    "unity",
    "ue4",
    "ue5",
    "3d",
    ".net",
    "php",
    "wpf",
    "开发媒介",
    "c语言开发",
    "c++软件开发",
    "前端开发",
    "python开发",
    "go",
    "算法",
    "c#",
]
company_block_list = [
    "乌鲁木齐",
    "京北方",
    "辛可必",
    "信息咨询",
    "美婷",
    "富联富桂",
    "培训",
    "职业",
    "中介",
    "学校",
    "人力",
    "童星",
    "儿童",
    "童画",
    "童美",
    "工艺",
    "青萍",
    "喜悦",
    "派森特",
    "沐雨禾禾",
    "中电金信",
    "广日电梯",
    "压寨",
    "合伙",
    "中科软",
    "汉科软",
    "快酷",
    "奥特",
    "原子云",
    "泛微",
    "创业",
    "图墨",
    "易科士",
    "老乡鸡",
    "美淘淘",
    "麦田房产",
    "招商银行",
    "格林豪泰",
    "佰钧成",
    "我爱我家",
    "地产",
    "宸鸿",
    "华众万象",
    "丹迪兰",
    "劲爆",
    "天玑科技",
    "华众科技",
    "百思科技",
    "绣歌",
    "通力互联",
    "北京银行",
    "房产",
    "房屋",
    "销售",
    "投资咨询",
    "咨询管理",
    "品牌",
    "再生资源",
    "玻璃",
    "教育咨询",
    "教育信息咨询",
    "文化传承",
    "文化传媒",
    "经纪",
    "旅馆",
    "餐厅",
    "宾馆",
    "摄影",
    "啦啦",
    "旅游开发",
    "法律咨询",
    "文艺创作",
    "水处理",
    "合作社",
    "婚纱",
    "信用卡",
    "维修",
    "轿车",
    "尔希",
    "名人",
    "演员",
    "钟表",
    "网吧",
    "注册",
    "托管",
    "美嘉林",
    "海绵",
    "家居",
    "担保",
    "养殖",
    "汽修",
    "塑料",
    "面包房",
    "艺术",
    "蛋糕",
    "调味品",
    "小吃",
    "早教",
    "宠物",
    "保险",
    "装饰",
    "农场",
    "假日",
    "园艺",
    "代理",
    "练字",
    "书法",
    "书画",
    "器材",
    "烘培",
    "焊业",
    "歌城",
    "美容",
    "少儿",
    "美术",
    "门窗",
    "人力市场",
    "信用管理",
    "建材",
    "机械制造",
    "模具",
    "建筑工程",
    "配件",
    "服装",
    "健身",
    "化妆",
    "美颜",
    "加盟",
    "皇家",
    "花苑",
    "舞蹈",
    "农产品",
    "小镇",
    "直营",
    "托育",
    "工会",
    "练习",
    "宏源电子",
    "鞋业",
    "鞋厂",
    "叮咚",
    "卓杭",
    "商场",
    "商行",
    "经营部",
    "策马科技",
    "任拓",
]
fund_min = 29.0
res = 31536000
guide_block_list = [
    "地产中介",
    "销售",
    "采购",
    "电梯工",
    "药剂",
    "教师",
    "电气",
    "焊工",
    "前厅",
    "酒店",
    "广告制作",
    "配送",
    "摄影",
    "摄像",
    "水电",
    "制片",
]
update = 2592000
offline_interview = true
offline_city_list = ["杭州", "嘉兴", "苏州", "上海"]
description_min = 35
description_keyword_list = [
    "java",
    "python",
    "c++",
    "spring",
    "sql",
    "linux",
    "j2ee",
    "web",
    "app",
    "bug",
    "数据库",
    "后端",
    "软件",
    "程序",
    "代码",
    "开发",
    "计算机",
    "编程",
]
description_block_list = [
    "机房管理",
    "网络维护",
    "电话跳线",
    "机房线架",
    "监控系统",
    "门禁系统",
    "电子围栏",
    "硬件维护",
    "调音师",
    "轮班",
    "倒班",
    "排班",
    "夜班",
    "7*24",
    "7x24",
    "婚礼策划",
    "咨询师",
    "英文面试",
    "英语面试",
    "abview",
    "unity",
    "django",
    "tornado",
    "flask",
    "ue引擎",
    "3d引擎",
    "标书制作",
    "市场推广",
    "呼叫",
    "仪器设备",
    "信号采集",
    "驾照",
    "红绿灯",
    "维护维修",
    "燃气",
    "热水器",
    "钣金",
    "分子生物",
    "细胞生物",
    "模具",
    "样品",
    "贴片机",
    "字/分钟",
    "机台",
    "验机",
    "大型设备",
    "卫星",
    "体育运动",
    "引体向上",
    "俯卧撑",
    "挖掘客户",
    "java勿扰",
    "没有编程",
    "不接受应届",
    "不接收应届",
    "不考虑应届",
    "应届生请勿",
    "联系回访",
    "商机",
    "快手",
    "抖音",
    "陪产",
    "临床护理",
    "小红书",
    "反应堆",
    "测试组长",
    "低功耗产品开发",
    "运维通信",
    "能力稍逊",
    "资产登记",
    "电厂",
    "nbt200",
    "iec621",
    "镭雕",
    "激光电视",
    "投影产品",
    "视频号",
    "开发客户",
    "智能手表",
    "商务对接",
    "卫生工作",
    "城乡规划",
    "资源管理",
    "专利代理",
    "photoshop",
    "湘源",
    "sketchup",
    "财务",
    "会计",
    "审计",
    "财税",
    "能直播",
    "保管与申购",
    "车模",
    "直播经验",
    "应届生勿",
    "日语",
    "无线电",
    "内核裁剪",
    "驱动开发",
    "密码学",
    "证书管理",
    "ipsec",
    "vpn",
    "vpp",
    "sonic",
    "frr",
    "cvi",
    "dpdk",
    "rs232",
    "rs485",
    "rs422",
    "洗衣机",
    "熟悉opencv",
    "熟悉hyper",
    "检查设备",
    "摩擦性能",
    "三坐标",
    "剪切测试",
    "硬度测试",
    "温度测试",
    "精通c#",
    "精通.net",
    "掌握c#",
    "会c#",
    "熟悉c#",
    "熟悉.net",
    "熟悉win",
    "熟悉wpf",
    "熟悉图像处理",
    "熟悉三维",
    "熟练运用c#",
    "熟练使用php",
    "爬虫经验",
    "算法经验",
    "熟练操作vb",
    "精通lab",
    "qt语言基础",
    "xamarin",
    "mcu",
    "dicom",
    "visuallisp",
    "vba",
    "vs.net",
    "asp.net",
    "sfcs",
    "ads",
    "objectarx",
    "finereport",
    "dsp",
    "ecu",
    "uds",
    "cdd",
    "diva",
    "整机测试",
    "设备及仪器",
    "蓝牙耳机",
    "游戏测试",
    "汽车",
    "驾驶",
    "车厂",
    "机器人",
    "硬件控制",
    "单片",
    "机顶盒",
    "电机",
    "串口",
    "布线",
    "上位",
    "销售",
    "营销",
    "车间",
    "车型",
    "家具",
    "电路",
    "电气",
    "弱电",
    "变频",
    "plc",
    "pms",
    "配电",
    "电力",
    "电子工艺",
    "新材料",
    "物料",
    "家电",
    "电能",
    "采购",
    "美妆",
    "污染",
    "大气",
    "危废",
    "气动",
    "液压",
    "电控",
    "电池",
    "给排水",
    "限温",
    "水利",
    "水务",
    "水文",
    "水资源",
    "化工",
    "石油",
    "土建",
    "安防产品",
    "手机厂商",
    "请勿联系",
    "兼职",
    "质检员",
    "退货",
    "水泵",
    "原标题",
    "软著",
    "课程",
    "老师",
    "家长",
    "样衣",
    "面辅料",
    "3d设计",
    "3d渲染",
    "犀牛软件",
    "三维建模",
    "频谱",
    "示波器",
    "万用表",
    "分析仪",
    "焊接",
    "电子元器件",
    "车载",
    "酷家乐",
    "面料",
    "女装",
    "汽车行业",
    "墨滴",
    "喷射",
    "喷头",
    "材料化学",
    "机械制图",
    "喷墨",
    "供墨系统",
    "首饰",
    "打板",
    "售后问题",
    "客情关系",
    "客户上门",
    "所属片区",
    "打字速度",
    "全屋定制",
    "华广软件",
    "定制家具",
    "驻店",
    "造诣软件",
    "交换机",
    "不是软件",
    "土木",
    "机械相关",
    "生产设备",
    "质检",
    "平面设计",
    "纺织",
    "无人机",
    "家纺",
    "会员群",
    "货品调配",
    "*****",
    "v50",
    "82800",
    "tr6850",
    "protel",
    "pcb",
    "大学2字",
    "暂挂",
    "简历收集",
    "非立即入职",
    "没有空缺",
    "天猫商家",
    "钉群管理",
    "电商开店",
    "泛微招聘",
    "甲方～",
    "外貌要求",
    "恕不退还",
    "已找到",
    "携带相关证件",
    "6级或以上",
    "21年及之前",
    "焊点",
    "211以上",
    "211本科以上",
    "211本科及以上",
]
description_experience_block_list = [
    "在校生",
    "在读",
    "大一",
    "大二",
    "大三",
    "大四",
    "研二",
    "研三",
    "研一",
    "年以上",
    "年及以上",
    "年或以上",
    "1-3年",
    "1-2年",
    "2-3年",
    "3～5年",
    "三年",
    "3年",
    "二年",
    "2年",
    "两年",
    "4年",
    "5年",
    "年(含)以上",
]
query_list = [
    "Java",
    "Java软件开发",
    "软件测试",
    "软件自动化测试",
    "软件功能测试",
    "软件实施",
    "全栈工程师",
    "Python软件测试",
    "软件测试开发",
    "软件性能测试",
    # "软件技术文档",
    # "数据分析",
    # "数据挖掘",
    # "软件需求分析",
    # "Node.js",
    # "Python",
    # "DBA",
    # "Hadoop",
    # "JavaScript",
    "Java&position=100101", # Java
    "Java&position=100305", # 测试开发
    "&position=100309",     # 软件测试
    "软件测试&position=100301", # 测试工程师
    "软件测试&position=100302", # 自动化测试
    "软件测试&position=100303", # 功能测试
    "Java&position=100606", # 实施
    # "Java&position=100123",   # 全栈工程师
    # "&position=100123",       # 全栈工程师
    # "Java&position=100402",   # 运维开发
    # "软件运维开发&position=100402", # 运维开发
    # "软件运维&position=100401", # 运维
]
query_city_list = [
    "100010000", # 全国
    "101210100", # 杭州
    "101020100", # 上海
    "101010100", # 北京
    "101280100", # 广州
    "101280600", # 深圳
    "101190400", # 苏州
    "101190100", # 南京
    "101200100", # 武汉
    "101250100", # 长沙
    "101270100", # 成都
]
query_param = "&experience=101,102,103,104&scale=302,303,304,305,306&degree=209,208,206,202,203"
salary_list = ["404", "403"]
page_min = 1
page_max = 10
