name: Gemini-OpenAI-Proxy Deploy

on:
  schedule:
    - cron: "0 18 * * 3"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1
        with:
          repository: "zuisong/gemini-openai-proxy"
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@1.11.0
        with:
          project: gemini-openai-proxy
          entrypoint: dist/main_deno.mjs
          include: dist/main_deno.mjs
