name: zhipinApi

on:
  workflow_dispatch:

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          sudo apt-get install -y language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r zhipin/requirements.txt
      - uses: robinraju/release-downloader@v1.9
        with:
          tag: "zhipin"
          fileName: "*.json"
          out-file-path: "zhipin"
      - name: Run zhipinApi.py
        env:
          STATE: ${{ vars.STATE }}
          CONFIG_URL: ${{ vars.CONFIG_URL }}
          DB_URL: ${{ secrets.DB_URL }}
          PROXY_URL: ${{ vars.PROXY_URL }}
          CF_API_GATEWAY: ${{ secrets.CF_API_GATEWAY }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLIP_URL: ${{ secrets.CLIP_URL }}
        run: |
          cd zhipin
          python zhipinApi.py
      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          path: |
            zhipin/*.txt
            zhipin/*.json
            zhipin/*.xml
            zhipin/junit/*
            zhipin/latest_logs/*/*
      - uses: ncipollo/release-action@v1
        if: always()
        with:
          artifacts: "zhipin/*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
