name: zhipin

on:
  workflow_dispatch:

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          sudo apt-get install -y language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          curl https://raw.githubusercontent.com/seleniumbase/SeleniumBase/master/requirements.txt --output requirementsSeleniumBase.txt
          pip install -r requirementsSeleniumBase.txt
          pip install -r BossRS-helper/requirements.txt
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Check the console scripts interface
        run: |
          seleniumbase
          sbase
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
      - name: Make sure pytest is working
        run: |
          echo "def test_1(): pass" > nothing.py
          pytest nothing.py
      - name: Make sure nosetests is working
        run: |
          echo "def test_2(): pass" > nothing2.py
          nosetests nothing2.py
      - name: Run pytest BossRS-helper/zhipin.py
        env:
          STATE: ${{ vars.STATE }}
          CONFIG_PATH: ${{ vars.CONFIG_PATH }}
          PROXY_STR: ${{ vars.PROXY_STR }}
        run: |
          cd BossRS-helper
          pytest zhipin.py --uc --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          path: |
            ./*.txt
            ./*.xml
            BossRS-helper/*.db
            BossRS-helper/*.txt
            BossRS-helper/*.json
            BossRS-helper/*.xml
            BossRS-helper/junit/*
            BossRS-helper/latest_logs/*/*
