name: zhipinBase

on:
  schedule:
    - cron: "0 6,18 * * *"
  workflow_dispatch:
    inputs:
      args:
        description: "Use args"
        required: false
        default: " -n3 "
        type: string

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          sudo apt-get install -y language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r zhipin/requirements.txt
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Check the console scripts interface
        run: |
          seleniumbase
          sbase
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
          seleniumbase install uc_driver
      - name: Make sure pytest is working
        run: |
          echo "def test_1(): pass" > nothing.py
          pytest nothing.py
      - name: Make sure nosetests is working
        run: |
          echo "def test_2(): pass" > nothing2.py
          nosetests nothing2.py
      - name: Set execute permissions
        run: |
          sudo chmod +x /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver
      - uses: robinraju/release-downloader@v1.9
        with:
          tag: "zhipin"
          fileName: "*.json"
          out-file-path: "zhipin"
      - run: |
          chmod +x sh/wireguard.sh
          sudo bash sh/wireguard.sh
      - name: Run pytest zhipinBase.py
        env:
          STATE: ${{ vars.STATE }}
          CONFIG_URL: ${{ vars.CONFIG_URL }}
          DB_URL: ${{ secrets.DB_URL }}
          PROXY_URL: ${{ vars.PROXY_URL }}
          CF_API_GATEWAY: ${{ secrets.CF_API_GATEWAY }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLIP_URL: ${{ secrets.CLIP_URL }}
        run: |
          cd zhipin
          pytest zhipinBase.py --uc --browser=chrome --headless ${{ inputs.args }} --chromium-arg="--proxy-server=$PROXY_URL"  -v -s --junit-xml=junit/test-results.xml
      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          path: |
            zhipin/*.txt
            zhipin/*.json
            zhipin/*.xml
            zhipin/junit/*
            zhipin/latest_logs/*/*
      - uses: ncipollo/release-action@v1
        if: always()
        with:
          artifacts: "zhipin/*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
